### ISSUE TITLE
Incorrect name on pypi

### ISSUE THREAD

**Issue by aswgxf** [SamHDev/inspiro#1]
Pypi still has the name insprio instead of inspiro.

**Comment by SamHDev** [comment]
Ta. 
Fixed my inability to spell.

https://pypi.org/project/inspiro/

**Comment by aswgxf** [comment]
Somewhat related, the Homepage link on PyPI points to "https://github.com/samhdev/insprio".

**Comment by SamHDev** [comment]
also fixed :)
