### ISSUE TITLE
"no module named Inspirobot"

### ISSUE THREAD

**Issue by SignalSender** [SamHDev/inspiro#2]
whenever i try to start my code it says "no module named Inspirobot" and points me towards the line "Import inspirobot" at the start of my code. it has been working fine for weeks but it seems like today it has decided to break.

**Comment by SamHDev** [comment]
Hello.

I've just installed the library and it seems to work fine for me.

Could you post what version of python your using (`path/to/python3 -V`) so I can try to reproduce the error?

- Sam.

**Comment by SignalSender** [comment]
I uninstalled and reinstalled the package and it works again. I think the issue might've been the website I was using. Thank you for the response though!
